name: absent_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-134.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: ^2.3.1
  get_storage: ^2.0.3 
  http: ^0.13.4
  flutter: 
    sdk: flutter
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/img/

